### ISSUE TITLE
Crop protector not working properly

### ISSUE THREAD

**Issue by lancer1977** [OCB7D2D/OcbLawnMowing#7]
It doesn't hurt seeds or growing plants, but it also doesn't allow us to mow down any fully grown plants.

**Comment by mgreter** [comment]
Are you sure you have the "Crop Harvester" installed too? As that one is required to harvest grown plants.

**Comment by lancer1977** [comment]
Thanks, so I figured it out, I had the protector and the harvester both installed where it seems the harvester also acts as the protector.
