### ISSUE TITLE
mod compatability issue when playing with 21.2 build of Darkness Falls

### ISSUE THREAD

**Issue by bluethunder1080** [OCB7D2D/OcbLawnMowing#8]
![image](https://github.com/OCB7D2D/OcbLawnMowing/assets/33799967/1fef43d0-1ecb-46b3-889a-523e08e7cbde)
![image](https://github.com/OCB7D2D/OcbLawnMowing/assets/33799967/720551c7-2281-4f4f-8836-89d8eb5951cb)

when playing on darkness falls modpack, trying to access Lawn Tractor Chassis from any menu to see crafting requirements, get that flood of text. same thing happens when accessing it via your inventory, metal workstation, laser workbench

does not give any issues if you buy/find/spawn the items, nor crafting the main recipe to make the tractor.

as for build, 
7DTD 21,2,
DF is for 21.2
[OCB Lawn Tractor (A21)](https://www.nexusmods.com/7daystodie/mods/3312)
[PGz Trader Jen Announcements A21](https://www.nexusmods.com/7daystodie/mods/3482)

changing the Unlocked by tag appears to fix the crashing issue, but had to make the changes on items.a21.xml....changing it in items.df.xml appeared to make no change
<property name="UnlockedBy" value="perkLivingOffTheLand,perkBasicFarming"/>

**Comment by mgreter** [comment]
Sorry, haven't added back compatibility for new A21 DF yet, simple as that!
Should probably just be xml stuff, but no idea if or when I will get around to do it.
