### ISSUE TITLE
Question(s)

### ISSUE THREAD

**Issue by Fireworkstars46** [OCB7D2D/OcbLawnMowing#9]
Does this mod have discord?

**Comment by mgreter** [comment]
Not really, I only am present on guppy's modding discord.
1st level support is mostly done via nexusmods.
Bug reports with logs etc. can be posted on GitHub.

**Comment by Fireworkstars46** [comment]
Another question I have is, would the lawn tractor break plant fibers/grass inside or on the border of the trader? Like the blocks by default is not breakable by player in the traders area but would the mod be able to or would it not do anything?

**Comment by mgreter** [comment]
Don't know, don't remember I ever tried it ...

**Comment by Fireworkstars46** [comment]
Also does enabling the cutting setting use more gas than having it off or is it the same gas consumption both ways?

**Comment by mgreter** [comment]
As already written in the journal entry (RTFM maybe), it uses more.

**Comment by Fireworkstars46** [comment]
So it uses more?
